AAudio: don't count the time of stopped stream and replace stop request with pause.
mozilla/cubeb pull request #789
Opened 2024-06-21 03:40 UTC by jhlin

If a stream has previously been stopped and then started, the elapsed time in between should not be included when calculating the position.

Also, `AAudioStream_requestStop()` doesn't behave as expected.

2024-06-21 16:22 UTC, padenot requested changes

2024-06-21 16:22 UTC, padenot commented on src/cubeb_aaudio.cpp
> +  std::mutex mutex;
Unfortunately, we can't use locks here because we're on a real-time thread. Thankfully, we only have a few arithmetic operations to do here so we can use `std::atomic`.

2024-06-22 01:30 UTC, jhlin commented on src/cubeb_aaudio.cpp
> +  std::mutex mutex;
Thanks a lot for the review! I've updated the logic to use `std::atomic` rather than `std::mutex`. Please let me know if any issues.

2024-06-26 20:15 UTC, jhlin commented
In the latest revision, the synchronization logic was removed—access to states/values only in user-called functions.

2024-06-26 20:52 UTC, jhlin commented
Not sure why [the test failed on Windows](https://github.com/mozilla/cubeb/actions/runs/9686094771/job/26727735282?pr=789). The patches only affect Android behavior.

2024-06-27 16:47 UTC, jhlin commented
@Pehrsons @padenot suggested I seek your help for review. Could you please help? Please let me know if you have any questions. Thanks!

2024-06-27 20:19 UTC, Pehrsons commented
The windows failure is probably an intermittent. It succeeded after a re-run.

Just looking fundamentally at this I am on board with fixing the interpolation (we also have other issues in the area, see https://bugzilla.mozilla.org/show_bug.cgi?id=1902263).
But why do we want to pause rather than stop? Is the concern that `AAudioStream_requestStop` flushes, so throws away some data that we lose track of?

I see an issue:
If the client calls `AAudioStream_requestPause` via `cubeb_stream_stop`, then after some time and some seeks (i.e. the next audio frame the client will write is not immediately after the last frame it wrote) have passed, it calls `AAudioStream_requestStart` via `cubeb_stream_start`, wouldn't the `AAudioStream` initially play old audio? That seems wrong.

That the flushed data doesn't reach the user's ears doesn't seem like a problem. It's short enough so they're unlikely to notice. For the sake of `cubeb_stream_get_position` though, we should probably treat the flushed audio as played.

Let me know if I understood this right!

2024-06-27 22:10 UTC, jhlin commented
Thanks a lot for the review!

> The windows failure is probably an intermittent. It succeeded after a re-run.
> 
> Just looking fundamentally at this I am on board with fixing the interpolation (we also have other issues in the area, see https://bugzilla.mozilla.org/show_bug.cgi?id=1902263). But why do we want to pause rather than stop? Is the concern that `AAudioStream_requestStop` flushes, so throws away some data that we lose track of?

Exactly, the already buffered data in the previous data callback will be flushed by `AAudioStream_requestStop()` but not `AAudioStream_requestPause()`.

> 
> I see an issue: If the client calls `AAudioStream_requestPause` via `cubeb_stream_stop`, then after some time and some seeks (i.e. the next audio frame the client will write is not immediately after the last frame it wrote) have passed, it calls `AAudioStream_requestStart` via `cubeb_stream_start`, wouldn't the `AAudioStream` initially play old audio? That seems wrong.

Luckily, seeking destroys then initializes audio stream, so old data isn't played.

> 
> That the flushed data doesn't reach the user's ears doesn't seem like a problem. It's short enough so they're unlikely to notice. For the sake of `cubeb_stream_get_position` though, we should probably treat the flushed audio as played.

TBH, I never noticed skipped audio. I only found that some video frames were dropped when resuming a paused video because the audio clock advanced further than expected. This change didn't eliminate the issue completely in my tests, but it seems mitigated.

Besides, this behavior seems inconsistent with the other backends.

> 
> Let me know if I understood this right!

2024-06-28 09:32 UTC, Pehrsons commented
> Luckily, seeking destroys then initializes audio stream, so old data isn't played.

Ok, so that's true for Gecko but might not be for other clients.

> TBH, I never noticed skipped audio. I only found that some video frames were dropped when resuming a paused video because the audio clock advanced further than expected. This change didn't eliminate the issue completely in my tests, but it seems mitigated.

Makes sense that some dropped video frames is more noticable.

> Besides, this behavior seems inconsistent with the other backends.

Out of curiosity I went through the common ones as I'm not familiar with all:
- CoreAudio [is unclear](https://developer.apple.com/documentation/audiotoolbox/1440513-audiooutputunitstop?language=objc).
- Pulse [corks, which doesn't flush](https://freedesktop.org/software/pulseaudio/doxygen/stream_8h.html#a14e698233ac2d246646651955ab0ec7b), unless the data cb already told it to drain, then it [waits for the drain](https://searchfox.org/mozilla-central/rev/6b17ef1f53b0bc68a0d746599c01ad8723c80880/third_party/rust/cubeb-pulse/src/backend/stream.rs#652-657).
- Wasapi [doesn't seem to flush](https://learn.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-stop).

Paul confirms that cubeb_stream_stop is more for pausing also, let me take a deeper look in a bit.

2024-06-28 09:56 UTC, Pehrsons reviewed
Some early feedback. I'll have to look closer at the interpolator later.

2024-06-28 09:56 UTC, Pehrsons commented on src/cubeb_aaudio.cpp
> -          (!ostate || ostate == AAUDIO_STREAM_STATE_STOPPED)) {
It seems to me stopping and stopped should be considered invalid or handled.

2024-06-28 09:56 UTC, Pehrsons commented on src/cubeb_aaudio.cpp
> +  std::variant<uint64_t, uint64_t> time;
If these `uint64_t`s could be distinct types so you can do something like `std::get<StopTimestamp>(time)`, I think this would be easier to read.

2024-06-28 09:56 UTC, Pehrsons commented on src/cubeb_aaudio.cpp
> +class position_interpolator {
Please give a high-level overview of what this class' intended behavior is. Expected inputs and outputs and that sort of thing.

2024-06-28 09:56 UTC, Pehrsons commented on src/cubeb_aaudio.cpp
> +      // Has been stopped: calculate elipsed time.
s/elipsed/elapsed/
(and below)

2024-06-28 16:07 UTC, Pehrsons approved these changes
The logic seems to check out to me, thanks!
I left some ideas for making it easier to read. Do with them as you wish.
I also left a comment about AAUDIO_STREAM_STATE_{STOPPING|STOPPED}. Please at a minimum address this one before landing.

2024-07-04 01:10 UTC, jhlin commented on src/cubeb_aaudio.cpp
> -          (!ostate || ostate == AAUDIO_STREAM_STATE_STOPPED)) {
Sorry but I don't follow. In the patch, only `AAUDIO_STREAM_STATE_{PAUSING|PAUSED}` are allowed, and `AAUDIO_STREAM_STATE_{STOPPING|STOPPED}` are considered invalid. Am I missing something?

2024-07-04 01:11 UTC, jhlin commented on src/cubeb_aaudio.cpp
> +  std::variant<uint64_t, uint64_t> time;
Good idea. I will do it in the next revision. Thanks!

2024-07-04 01:29 UTC, jhlin commented on src/cubeb_aaudio.cpp
> +class position_interpolator {
> Please give a high-level overview of what this class' intended behavior is. Expected inputs and outputs and that sort of thing.

I will add comments for the class in the next revision.

> It seems to me we are really tracking the time spent in the starting/started states with a stale callback timestamp.

Agree. Calling `AAudioStream_requestStop()` does generate a new callback invocation immediately after starting to get more data, but since it flushes previously buffered data, the position always jumps ahead, and video frames get dropped. I hope calling `AAudioStream_requestPause()` can make it less serious.

2024-07-04 08:06 UTC, Pehrsons commented on src/cubeb_aaudio.cpp
> -          (!ostate || ostate == AAUDIO_STREAM_STATE_STOPPED)) {
Re invalid I was thinking higher up under `handle invalid stream states`. Maybe we cannot do that because we still call `AAudioStream_requestStop` in some other cases?

2024-07-04 16:49 UTC, jhlin commented on src/cubeb_aaudio.cpp
> -          (!ostate || ostate == AAUDIO_STREAM_STATE_STOPPED)) {
Thanks for the explanation. Yes, since [`AAudioStream_requestStop()` is called in case `stream_state::DRAINING`](https://github.com/mozilla/cubeb/blob/master/src/cubeb_aaudio.cpp#L406), I don't think `AAUDIO_STREAM_STATE_{STOPPING|STOPPED}` need to be listed in the `handle invalid stream states` conditions.

2024-07-08 16:08 UTC, merged